The-Agile-Avengers/icu-connect-frontend

.eslintrc.cjs
package-lock.json
package.json
src/App.tsx
src/ProTip.tsx
src/components/Copyright.tsx
src/components/LoginForm.tsx
src/components/SignUpForm.tsx
src/components/rounting/AppRounter.tsx
src/components/shared/Layout.tsx
src/components/shared/types.ts
src/index.tsx
src/theme.ts

U14: Typescript Refactor

---

.eslintrc.cjs
.github/workflows/ci_cd_pipeline.yml
Dockerfile
README.md
docker-compose.yml

New CI/CD Pipeline

---

src/pages/LoginPage.tsx
src/utils/api.ts
src/utils/utils.ts

Fixes the management of the JwtToken in our React app.

U15: Fix JwtToken Management

---

src/components/course/review/CourseReviewForm.tsx

U9: create review is sent to backend, and form is reset

---

src/components/course/CourseInfo.tsx
src/components/course/ratingIcons.tsx

U03: Display Course Content in Info Box 

---

src/components/shared/Layout.tsx

Fixes the Layout, such that it is responsive again.

Fix Responsive Layout

---

.eslintrc.cjs
src/components/course/rating/CommunityRating.tsx
src/components/course/rating/CommunityRatingForm.tsx
src/models/CommunityModel.ts
src/pages/Community.tsx
src/utils/types.ts
tsconfig.json

closes #139 
closes #7
missing backend support: https://github.com/The-Agile-Avengers/icu-connect-backend/issues/47#issuecomment-1500946274

Add Rating Feature & Rating View

---

.eslintrc.cjs
src/components/course/rating/CommunityRating.tsx
src/components/course/rating/CommunityRatingForm.tsx
src/models/CommunityModel.ts
src/pages/Community.tsx
src/utils/types.ts
tsconfig.json

⚠️ Please merge https://github.com/The-Agile-Avengers/icu-connect-frontend/pull/152 first! ⚠️ 
closes #28 
closes #29 
closes #30 
closes #31 
closes #153

Add Join/Leave Community functionality

---

src/components/course/rating/CommunityRatingForm.tsx

bug: require all ratings to submit

---

src/components/course/post/CommunityPost.tsx
src/components/course/post/CommunityPostForm.tsx
src/pages/Community.tsx
src/utils/types.ts

closes #11 
closes #34
closes #35 
closes #36

U7: show and create posts

---

src/components/course/post/CommentsSection.tsx
src/components/course/post/CommunityPost.tsx
src/components/course/post/CommunityPostForm.tsx
src/components/course/post/PostComment.tsx
src/pages/Community.tsx
src/utils/types.ts
src/utils/utils.ts

ATTENTION: First merge #157 !!
closes #37 
closes #38 
closes #39

U8: create comment and show comments to post

---

.github/workflows/ci_cd_pipeline.yml

Add AWS S3 Deployment

---

src/components/course/post/CommentsSection.tsx
src/utils/types.ts

Bug: disable button when comment empty

---

src/components/course/CommunityInfo.tsx
src/components/course/CreateCommunityForm.tsx
src/components/course/post/CommunityPostForm.tsx
src/components/course/rating/CommunityRating.tsx
src/components/course/rating/CommunityRatingForm.tsx
src/components/course/rating/HoverRating.tsx
src/components/navbar/Navbar.tsx
src/models/RatingModel.ts
src/pages/Community.tsx
src/pages/Settings.tsx

closes #15 
closes #98
closes #99 
Future work:

U12: As a registered user, I want to like ratings, I deem useful so that to express my support to ratings I deem useful

---

src/utils/api.ts
src/utils/utils.ts

Add outdated token handler

---

src/components/course/post/CommunityPost.tsx
src/components/course/post/PostComment.tsx
src/components/course/rating/CommunityRating.tsx
src/pages/Community.tsx
src/pages/Settings.tsx
src/utils/utils.ts

fix: show avatar in post and ratings

---

src/components/course/rating/CommunityRating.tsx
src/components/course/rating/CommunityRatingForm.tsx
src/utils/types.ts

Currently only works on this branch [feature/rs/U12-6-like-flag](https://github.com/The-Agile-Avengers/icu-connect-backend/tree/feature/rs/U12-6-like-flag)
closes #194

Feat: Display if user has already liked a rating or not

---

src/components/course/post/CommunityPostForm.tsx
src/pages/Community.tsx

ATTENTION: Please merge this first before merging #205
closes #20 
closes #111 
closes #112

U18:filter for posts per year

---

src/components/course/CommunityInfo.tsx
src/components/course/file/CummunityFiles.tsx
src/components/course/file/FileUpload.tsx
src/components/course/post/CommunityPostForm.tsx
src/pages/Community.tsx
src/utils/types.ts

ATTENTION: Please merge this as last! First merge #202 
closes #109
closes #110
closes #200

U17: Upload, download and delete files

---

src/pages/Login.tsx
src/pages/SignUp.tsx

Feat: Error Handling 

---

src/components/ShareButton.tsx
src/components/course/file/FileUpload.tsx
src/components/course/post/CommunityPostForm.tsx
src/components/course/rating/CommunityRatingForm.tsx
src/pages/Community.tsx
src/pages/Settings.tsx
src/utils/types.ts

feature: add autocomplete study area

---

src/components/LogoutButton.tsx
src/components/course/rating/CommunityRating.tsx
src/components/course/rating/HoverRating.tsx
src/components/navbar/Navbar.tsx
src/pages/Community.tsx
src/utils/api.ts
src/utils/utils.ts

closes #206 
closes #207
closes #209

fix: add logout and fix rating and spelling

---

README.md
public/manifest.json
src/components/course/CommunityBox.tsx
src/components/shared/Layout.tsx
src/design/theme.ts
src/design/typography.tsx
src/pages/Communities.tsx

closes #220 
closes #223 
closes #222 
closes #215

Final Changes 
